# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('Data', models.FileField(upload_to=b'uploads/')),
            ],
        ),
    ]
