# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20170427_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 29, 23, 28, 27, 402626, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 29, 23, 28, 39, 855390, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
