# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20170429_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='Data',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
