# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 29, 13, 36, 59, 578290, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 29, 13, 37, 25, 716527, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 29, 13, 37, 43, 750442, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 29, 13, 37, 57, 598753, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
